//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos;/&gt;
        ///
        ///  &lt;!-- разделитель строк входного файла--&gt;
        ///  &lt;xsl:param name=&apos;rowDelimiter&apos;&gt;\r?\n&lt;/xsl:param&gt;
        ///
        ///  &lt;!-- преобразуемая информация, во время выполнения подменяется значениями из входных файлов от определенного ДООО  --&gt;
        ///  &lt;!-- ASTRA_IMPORT_CS&lt;ddmmyyyyHHmi&gt;.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASTRA_Import_CSHOP {
            get {
                return ResourceManager.GetString("ASTRA_Import_CSHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos;/&gt;
        ///
        ///  &lt;!-- разделитель строк входного файла--&gt;
        ///  &lt;xsl:param name=&apos;rowDelimiter&apos;&gt;\r?\n&lt;/xsl:param&gt;
        ///  
        ///  &lt;!-- преобразуемая информация, во время выполнения подменяется значениями из входных файлов от определенного ДООО  --&gt;
        ///
        ///  &lt;xsl:param name=&apos;inputContent&apos; a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASTRA_Import_PIPE {
            get {
                return ResourceManager.GetString("ASTRA_Import_PIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos;
        ///                xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos;/&gt;
        ///  &lt;xsl:param name=&apos;input&apos; as=&apos;xs:string&apos;   &gt;
        ///  &lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&apos;delimiter&apos; &gt;,&lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&apos;regex&apos; &gt;
        ///    ^\s*([^:]*)\s*:\s*([^:]*)\s*:[^:]*$
        ///  &lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&apos;lookupTableParam&apos;&gt;
        ///    &lt;val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtg_utg {
            get {
                return ResourceManager.GetString("mtg_utg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos;
        ///                xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos; /&gt;
        ///  &lt;xsl:param name=&apos;input&apos; as=&apos;xs:string&apos;&gt;&lt;/xsl:param&gt;
        ///
        ///  &lt;xsl:param name=&apos;regex&apos;&gt;
        ///    ^\s*([^;]*)\s*;\s*([^;]*)\s*;\s*([^;]*)\s*$
        ///  &lt;/xsl:param&gt;
        ///  &lt;xsl:param name=&apos;lookupTableParam&apos; &gt;
        ///    &lt;!--&lt;LookupTable &gt;
        ///      &lt;Items&gt;
        ///        &lt;It [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samara {
            get {
                return ResourceManager.GetString("samara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos;/&gt;
        ///
        ///  &lt;!-- разделитель строк входного файла--&gt;
        ///  &lt;xsl:param name=&apos;rowDelimiter&apos;&gt;\r?\n&lt;/xsl:param&gt;
        ///  
        ///  &lt;!-- преобразуемая информация, во время выполнения подменяется значениями из входных файлов от определенного ДООО  --&gt;
        ///  &lt;xsl:param name=&apos;inputContent&apos; as= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAR_Import_GTMoscow_v1 {
            get {
                return ResourceManager.GetString("SAR_Import_GTMoscow_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos;/&gt;
        ///
        ///  &lt;!-- разделитель строк входного файла--&gt;
        ///  &lt;xsl:param name=&apos;rowDelimiter&apos;&gt;\r?\n&lt;/xsl:param&gt;
        ///
        ///  &lt;!-- преобразуемая информация, во время выполнения подменяется значениями из входных файлов от определенного ДООО  --&gt;
        ///  &lt;xsl:param name=&apos;inputContent&apos; as=&apos;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAR_Import_GTSamara_v1 {
            get {
                return ResourceManager.GetString("SAR_Import_GTSamara_v1", resourceCulture);
            }
        }
    }
}
