//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GazRouter.Modes.ExcelReports.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExcelReportCustomResouces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelReportCustomResouces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GazRouter.Modes.ExcelReports.Resources.ExcelReportCustomResouces", typeof(ExcelReportCustomResouces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Data_Clear {
            get {
                return ResourceManager.GetString("Data_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа с данными.
        /// </summary>
        public static string Data_DataTools {
            get {
                return ResourceManager.GetString("Data_DataTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка данных.
        /// </summary>
        public static string Data_DataValidation {
            get {
                return ResourceManager.GetString("Data_DataValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обвести неверные данные.
        /// </summary>
        public static string Data_DataValidation_CircleInvalidData {
            get {
                return ResourceManager.GetString("Data_DataValidation_CircleInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить обводку неверных данных.
        /// </summary>
        public static string Data_DataValidation_ClearValidationCircles {
            get {
                return ResourceManager.GetString("Data_DataValidation_ClearValidationCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string Data_Filter {
            get {
                return ResourceManager.GetString("Data_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить.
        /// </summary>
        public static string Data_Reapply {
            get {
                return ResourceManager.GetString("Data_Reapply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        public static string Data_Sort {
            get {
                return ResourceManager.GetString("Data_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка и фильтр.
        /// </summary>
        public static string Data_SortAndFilter {
            get {
                return ResourceManager.GetString("Data_SortAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка от А до Я.
        /// </summary>
        public static string Data_SortAtoZTooltip {
            get {
                return ResourceManager.GetString("Data_SortAtoZTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка от Я до А.
        /// </summary>
        public static string Data_SortZtoATooltip {
            get {
                return ResourceManager.GetString("Data_SortZtoATooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string File_New {
            get {
                return ResourceManager.GetString("File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string File_Open {
            get {
                return ResourceManager.GetString("File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string File_Print {
            get {
                return ResourceManager.GetString("File_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разобрать по копиям.
        /// </summary>
        public static string File_Print_Collated {
            get {
                return ResourceManager.GetString("File_Print_Collated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копии.
        /// </summary>
        public static string File_Print_Copies {
            get {
                return ResourceManager.GetString("File_Print_Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры страницы.
        /// </summary>
        public static string File_Print_PageSetup {
            get {
                return ResourceManager.GetString("File_Print_PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string File_Print_Print_ {
            get {
                return ResourceManager.GetString("File_Print_Print ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка.
        /// </summary>
        public static string File_Print_Settings {
            get {
                return ResourceManager.GetString("File_Print_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переворот горизонтальный.
        /// </summary>
        public static string FlipHorizontal {
            get {
                return ResourceManager.GetString("FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переворот вертикальный.
        /// </summary>
        public static string FlipVertical {
            get {
                return ResourceManager.GetString("FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие финансовые форматы.
        /// </summary>
        public static string Home_AccountingNumberFormat_MoreAccountingNumberFormat {
            get {
                return ResourceManager.GetString("Home_AccountingNumberFormat_MoreAccountingNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансовый числовой формат.
        /// </summary>
        public static string Home_AccountingNumberFormatTooltip {
            get {
                return ResourceManager.GetString("Home_AccountingNumberFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выравнивание.
        /// </summary>
        public static string Home_Alignment {
            get {
                return ResourceManager.GetString("Home_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выровнять текст по левому краю.
        /// </summary>
        public static string Home_AlignTextLeftTooltip {
            get {
                return ResourceManager.GetString("Home_AlignTextLeftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выровнять текст по правому краю.
        /// </summary>
        public static string Home_AlignTextRightTooltip {
            get {
                return ResourceManager.GetString("Home_AlignTextRightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полужирный (Ctrl+B).
        /// </summary>
        public static string Home_BoldCtrlBTooltip {
            get {
                return ResourceManager.GetString("Home_BoldCtrlBTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Границы.
        /// </summary>
        public static string Home_Borders {
            get {
                return ResourceManager.GetString("Home_Borders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все границы.
        /// </summary>
        public static string Home_Borders_AllBorder {
            get {
                return ResourceManager.GetString("Home_Borders_AllBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижняя граница.
        /// </summary>
        public static string Home_Borders_BottomBorder {
            get {
                return ResourceManager.GetString("Home_Borders_BottomBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нарисовать гарницы.
        /// </summary>
        public static string Home_Borders_DrawBorders {
            get {
                return ResourceManager.GetString("Home_Borders_DrawBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Левая граница.
        /// </summary>
        public static string Home_Borders_LeftBorder {
            get {
                return ResourceManager.GetString("Home_Borders_LeftBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет линии.
        /// </summary>
        public static string Home_Borders_LineColor {
            get {
                return ResourceManager.GetString("Home_Borders_LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        public static string Home_Borders_LineColor_Automatic {
            get {
                return ResourceManager.GetString("Home_Borders_LineColor_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартные цвета.
        /// </summary>
        public static string Home_Borders_LineColor_Colors {
            get {
                return ResourceManager.GetString("Home_Borders_LineColor_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета темы.
        /// </summary>
        public static string Home_Borders_LineColor_OficceColors {
            get {
                return ResourceManager.GetString("Home_Borders_LineColor_OficceColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид линии.
        /// </summary>
        public static string Home_Borders_LineStyle {
            get {
                return ResourceManager.GetString("Home_Borders_LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет границы.
        /// </summary>
        public static string Home_Borders_LineStyle_NoBorder {
            get {
                return ResourceManager.GetString("Home_Borders_LineStyle_NoBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие границы.
        /// </summary>
        public static string Home_Borders_MoreBorders {
            get {
                return ResourceManager.GetString("Home_Borders_MoreBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет границы.
        /// </summary>
        public static string Home_Borders_NoBorder {
            get {
                return ResourceManager.GetString("Home_Borders_NoBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешние границы.
        /// </summary>
        public static string Home_Borders_OutsideBorder {
            get {
                return ResourceManager.GetString("Home_Borders_OutsideBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правая граница.
        /// </summary>
        public static string Home_Borders_RightBorder {
            get {
                return ResourceManager.GetString("Home_Borders_RightBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толстая нижняя граница.
        /// </summary>
        public static string Home_Borders_ThickBottomBorder {
            get {
                return ResourceManager.GetString("Home_Borders_ThickBottomBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толстая внешняя граница.
        /// </summary>
        public static string Home_Borders_ThickBoxBorder {
            get {
                return ResourceManager.GetString("Home_Borders_ThickBoxBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхняя и нижняя границы.
        /// </summary>
        public static string Home_Borders_TopandBottomBorder {
            get {
                return ResourceManager.GetString("Home_Borders_TopandBottomBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхняя и толстая нижняя границы.
        /// </summary>
        public static string Home_Borders_TopandThickBottomBorder {
            get {
                return ResourceManager.GetString("Home_Borders_TopandThickBottomBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхняя граница.
        /// </summary>
        public static string Home_Borders_TopBorder {
            get {
                return ResourceManager.GetString("Home_Borders_TopBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По нижнему краю.
        /// </summary>
        public static string Home_BottomAlignTooltip {
            get {
                return ResourceManager.GetString("Home_BottomAlignTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ячейки.
        /// </summary>
        public static string Home_Cells {
            get {
                return ResourceManager.GetString("Home_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выровнять по центру.
        /// </summary>
        public static string Home_CenterTooltip {
            get {
                return ResourceManager.GetString("Home_CenterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Home_Clear {
            get {
                return ResourceManager.GetString("Home_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить все.
        /// </summary>
        public static string Home_Clear_ClearAll {
            get {
                return ResourceManager.GetString("Home_Clear_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить содержимое.
        /// </summary>
        public static string Home_Clear_ClearContents {
            get {
                return ResourceManager.GetString("Home_Clear_ClearContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить форматы.
        /// </summary>
        public static string Home_Clear_ClearFormats {
            get {
                return ResourceManager.GetString("Home_Clear_ClearFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить гиперссылки.
        /// </summary>
        public static string Home_Clear_ClearHyperlinks {
            get {
                return ResourceManager.GetString("Home_Clear_ClearHyperlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить гиперссылки.
        /// </summary>
        public static string Home_Clear_RemoveHyperlink {
            get {
                return ResourceManager.GetString("Home_Clear_RemoveHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буфер обмена.
        /// </summary>
        public static string Home_Clipboard {
            get {
                return ResourceManager.GetString("Home_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат с разделителями.
        /// </summary>
        public static string Home_CommaStyleTooltip {
            get {
                return ResourceManager.GetString("Home_CommaStyleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Home_Copy {
            get {
                return ResourceManager.GetString("Home_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать (Ctrl+С).
        /// </summary>
        public static string Home_CopyTooltip {
            get {
                return ResourceManager.GetString("Home_CopyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        public static string Home_Cut {
            get {
                return ResourceManager.GetString("Home_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать выделенное и положить в буфер обмена.
        /// </summary>
        public static string Home_CutDescription {
            get {
                return ResourceManager.GetString("Home_CutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить разрядность.
        /// </summary>
        public static string Home_DecreaseDecimalTooltip {
            get {
                return ResourceManager.GetString("Home_DecreaseDecimalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить размер шрифта.
        /// </summary>
        public static string Home_DecreaseFontSizeTooltip {
            get {
                return ResourceManager.GetString("Home_DecreaseFontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить отступ.
        /// </summary>
        public static string Home_DecreaseIndentTooltip {
            get {
                return ResourceManager.GetString("Home_DecreaseIndentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Home_Delete {
            get {
                return ResourceManager.GetString("Home_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить ячейки.
        /// </summary>
        public static string Home_Delete_DeleteCells___ {
            get {
                return ResourceManager.GetString("Home_Delete_DeleteCells...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить лист.
        /// </summary>
        public static string Home_Delete_DeleteSheet {
            get {
                return ResourceManager.GetString("Home_Delete_DeleteSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить столбцы с листа.
        /// </summary>
        public static string Home_Delete_DeleteSheetColumns {
            get {
                return ResourceManager.GetString("Home_Delete_DeleteSheetColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить строки с листа.
        /// </summary>
        public static string Home_Delete_DeleteSheetRows {
            get {
                return ResourceManager.GetString("Home_Delete_DeleteSheetRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить ячейки .
        /// </summary>
        public static string Home_DeleteCellsTooltip {
            get {
                return ResourceManager.GetString("Home_DeleteCellsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Home_Editing {
            get {
                return ResourceManager.GetString("Home_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнить.
        /// </summary>
        public static string Home_Fill {
            get {
                return ResourceManager.GetString("Home_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вниз.
        /// </summary>
        public static string Home_Fill_Down {
            get {
                return ResourceManager.GetString("Home_Fill_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влево.
        /// </summary>
        public static string Home_Fill_Left {
            get {
                return ResourceManager.GetString("Home_Fill_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вправо.
        /// </summary>
        public static string Home_Fill_Right {
            get {
                return ResourceManager.GetString("Home_Fill_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вверх.
        /// </summary>
        public static string Home_Fill_Up {
            get {
                return ResourceManager.GetString("Home_Fill_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет заливки.
        /// </summary>
        public static string Home_FillColorTooltip {
            get {
                return ResourceManager.GetString("Home_FillColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие цвета.
        /// </summary>
        public static string Home_FillColorTooltip_MoreColors {
            get {
                return ResourceManager.GetString("Home_FillColorTooltip_MoreColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет заливки.
        /// </summary>
        public static string Home_FillColorTooltip_NoFill {
            get {
                return ResourceManager.GetString("Home_FillColorTooltip_NoFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string Home_Find {
            get {
                return ResourceManager.GetString("Home_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        public static string Home_Font {
            get {
                return ResourceManager.GetString("Home_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер шрифта.
        /// </summary>
        public static string Home_FontSizeTooltip {
            get {
                return ResourceManager.GetString("Home_FontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        public static string Home_FontTooltip {
            get {
                return ResourceManager.GetString("Home_FontTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат.
        /// </summary>
        public static string Home_Format {
            get {
                return ResourceManager.GetString("Home_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоподбор ширины столбца.
        /// </summary>
        public static string Home_Format_AutofitColumnWidth {
            get {
                return ResourceManager.GetString("Home_Format_AutofitColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоподбор высоты строки.
        /// </summary>
        public static string Home_Format_AutoFitRowHeight {
            get {
                return ResourceManager.GetString("Home_Format_AutoFitRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер ячейки.
        /// </summary>
        public static string Home_Format_CellsSize {
            get {
                return ResourceManager.GetString("Home_Format_CellsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть столбцы.
        /// </summary>
        public static string Home_Format_HideColumns {
            get {
                return ResourceManager.GetString("Home_Format_HideColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть строки.
        /// </summary>
        public static string Home_Format_HideRows {
            get {
                return ResourceManager.GetString("Home_Format_HideRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать столбцы.
        /// </summary>
        public static string Home_Format_UnhideColumns {
            get {
                return ResourceManager.GetString("Home_Format_UnhideColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать строки.
        /// </summary>
        public static string Home_Format_UnhideRows {
            get {
                return ResourceManager.GetString("Home_Format_UnhideRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить разрядность.
        /// </summary>
        public static string Home_IncreaseDecimalTooltip {
            get {
                return ResourceManager.GetString("Home_IncreaseDecimalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить размер шрифта.
        /// </summary>
        public static string Home_IncreaseFontSizeTooltip {
            get {
                return ResourceManager.GetString("Home_IncreaseFontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить отступ.
        /// </summary>
        public static string Home_IncreaseIndentTooltip {
            get {
                return ResourceManager.GetString("Home_IncreaseIndentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string Home_Insert {
            get {
                return ResourceManager.GetString("Home_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить ячейки.
        /// </summary>
        public static string Home_Insert_InsertCells___ {
            get {
                return ResourceManager.GetString("Home_Insert_InsertCells...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить лист.
        /// </summary>
        public static string Home_Insert_InsertSheet {
            get {
                return ResourceManager.GetString("Home_Insert_InsertSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить столбцы на лист.
        /// </summary>
        public static string Home_Insert_InsertSheetColumns {
            get {
                return ResourceManager.GetString("Home_Insert_InsertSheetColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить строки на лист.
        /// </summary>
        public static string Home_Insert_InsertSheetRows {
            get {
                return ResourceManager.GetString("Home_Insert_InsertSheetRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить ячейки.
        /// </summary>
        public static string Home_InsertCellsTooltip {
            get {
                return ResourceManager.GetString("Home_InsertCellsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсив (Ctrl+I).
        /// </summary>
        public static string Home_ItalicCtrlITooltip {
            get {
                return ResourceManager.GetString("Home_ItalicCtrlITooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединить и центрировать.
        /// </summary>
        public static string Home_MergeAndCenter {
            get {
                return ResourceManager.GetString("Home_MergeAndCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединить по строкам.
        /// </summary>
        public static string Home_MergeAndCenter_MergeAcross {
            get {
                return ResourceManager.GetString("Home_MergeAndCenter_MergeAcross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединить и центрировать.
        /// </summary>
        public static string Home_MergeAndCenter_MergeAndCenter {
            get {
                return ResourceManager.GetString("Home_MergeAndCenter_MergeAndCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединить ячейки.
        /// </summary>
        public static string Home_MergeAndCenter_MergeCells {
            get {
                return ResourceManager.GetString("Home_MergeAndCenter_MergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить объединение ячеек.
        /// </summary>
        public static string Home_MergeAndCenter_UnmergeCells {
            get {
                return ResourceManager.GetString("Home_MergeAndCenter_UnmergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выровнять по середине.
        /// </summary>
        public static string Home_MiddleAlignTooltip {
            get {
                return ResourceManager.GetString("Home_MiddleAlignTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число.
        /// </summary>
        public static string Home_Number {
            get {
                return ResourceManager.GetString("Home_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Числовой формат.
        /// </summary>
        public static string Home_NumberFormatTooltip {
            get {
                return ResourceManager.GetString("Home_NumberFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string Home_Paste {
            get {
                return ResourceManager.GetString("Home_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина столбца.
        /// </summary>
        public static string Home_Paste_ColumnWidths {
            get {
                return ResourceManager.GetString("Home_Paste_ColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить (Ctrl+V).
        /// </summary>
        public static string Home_Paste_Ctrl_V_Tooltip {
            get {
                return ResourceManager.GetString("Home_Paste(Ctrl+V)Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форматирование.
        /// </summary>
        public static string Home_Paste_Formatting {
            get {
                return ResourceManager.GetString("Home_Paste_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формула.
        /// </summary>
        public static string Home_Paste_Formulas {
            get {
                return ResourceManager.GetString("Home_Paste_Formulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формула и числовой формат.
        /// </summary>
        public static string Home_Paste_FormulasAndNumberFormatting {
            get {
                return ResourceManager.GetString("Home_Paste_FormulasAndNumberFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие варианты вставки.
        /// </summary>
        public static string Home_Paste_OtherPasteOptions {
            get {
                return ResourceManager.GetString("Home_Paste_OtherPasteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить .
        /// </summary>
        public static string Home_Paste_Paste {
            get {
                return ResourceManager.GetString("Home_Paste_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения.
        /// </summary>
        public static string Home_Paste_Values {
            get {
                return ResourceManager.GetString("Home_Paste_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значения и числовой формат.
        /// </summary>
        public static string Home_Paste_ValuesAndNumberFormatting {
            get {
                return ResourceManager.GetString("Home_Paste_ValuesAndNumberFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процентный формат (Ctrl+Shift+%).
        /// </summary>
        public static string Home_PercentStyle_Ctrl_Shift___Tooltip {
            get {
                return ResourceManager.GetString("Home_PercentStyle(Ctrl+Shift+%)Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка и фильтр.
        /// </summary>
        public static string Home_SortAndFilter {
            get {
                return ResourceManager.GetString("Home_SortAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Home_SortAndFilter_Clear {
            get {
                return ResourceManager.GetString("Home_SortAndFilter_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string Home_SortAndFilter_Filter {
            get {
                return ResourceManager.GetString("Home_SortAndFilter_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить.
        /// </summary>
        public static string Home_SortAndFilter_Reapply {
            get {
                return ResourceManager.GetString("Home_SortAndFilter_Reapply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка от А до Я.
        /// </summary>
        public static string Home_SortAndFilter_SortAtoZ {
            get {
                return ResourceManager.GetString("Home_SortAndFilter_SortAtoZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка от Я до А.
        /// </summary>
        public static string Home_SortAndFilter_SortZtoA {
            get {
                return ResourceManager.GetString("Home_SortAndFilter_SortZtoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стили.
        /// </summary>
        public static string Home_Styles {
            get {
                return ResourceManager.GetString("Home_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет текста.
        /// </summary>
        public static string Home_TextHighlightColorTooltip {
            get {
                return ResourceManager.GetString("Home_TextHighlightColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        public static string Home_TextHighlightColorTooltip_Automatic {
            get {
                return ResourceManager.GetString("Home_TextHighlightColorTooltip_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие цвета.
        /// </summary>
        public static string Home_TextHighlightColorTooltip_MoreColors {
            get {
                return ResourceManager.GetString("Home_TextHighlightColorTooltip_MoreColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По верхнему краю.
        /// </summary>
        public static string Home_TopAlignTooltip {
            get {
                return ResourceManager.GetString("Home_TopAlignTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подчеркнутый (Ctrl+U).
        /// </summary>
        public static string Home_UnderlineCtrlUTooltip {
            get {
                return ResourceManager.GetString("Home_UnderlineCtrlUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенос текста.
        /// </summary>
        public static string Home_WrapText {
            get {
                return ResourceManager.GetString("Home_WrapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставка.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить гиперссылку.
        /// </summary>
        public static string Insert_AddaHyperlinkTooltip {
            get {
                return ResourceManager.GetString("Insert_AddaHyperlinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить рисунок из файла.
        /// </summary>
        public static string Insert_FromFileTooltip {
            get {
                return ResourceManager.GetString("Insert_FromFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гиперссылка.
        /// </summary>
        public static string Insert_Hyperlink {
            get {
                return ResourceManager.GetString("Insert_Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рисунок.
        /// </summary>
        public static string Insert_Pictures {
            get {
                return ResourceManager.GetString("Insert_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разметка страницы.
        /// </summary>
        public static string PageLayout {
            get {
                return ResourceManager.GetString("PageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрывы.
        /// </summary>
        public static string PageLayout_Breaks {
            get {
                return ResourceManager.GetString("PageLayout_Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить разрыв страницы.
        /// </summary>
        public static string PageLayout_Breaks_InsertPageBreak {
            get {
                return ResourceManager.GetString("PageLayout_Breaks_InsertPageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить разрыв страницы.
        /// </summary>
        public static string PageLayout_Breaks_RemovePageBreak {
            get {
                return ResourceManager.GetString("PageLayout_Breaks_RemovePageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс разрывов страниц.
        /// </summary>
        public static string PageLayout_Breaks_ResetAllPageBreak {
            get {
                return ResourceManager.GetString("PageLayout_Breaks_ResetAllPageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета.
        /// </summary>
        public static string PageLayout_Colors {
            get {
                return ResourceManager.GetString("PageLayout_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифты.
        /// </summary>
        public static string PageLayout_Fonts {
            get {
                return ResourceManager.GetString("PageLayout_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сетка.
        /// </summary>
        public static string PageLayout_Gridlines {
            get {
                return ResourceManager.GetString("PageLayout_Gridlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string PageLayout_Gridlines_Print {
            get {
                return ResourceManager.GetString("PageLayout_Gridlines_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать сетки.
        /// </summary>
        public static string PageLayout_Gridlines_PrintTooltip {
            get {
                return ResourceManager.GetString("PageLayout_Gridlines_PrintTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string PageLayout_Gridlines_View {
            get {
                return ResourceManager.GetString("PageLayout_Gridlines_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отобразить сетку.
        /// </summary>
        public static string PageLayout_Gridlines_ViewTooltip {
            get {
                return ResourceManager.GetString("PageLayout_Gridlines_ViewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовки.
        /// </summary>
        public static string PageLayout_Headings {
            get {
                return ResourceManager.GetString("PageLayout_Headings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string PageLayout_Headings_Print {
            get {
                return ResourceManager.GetString("PageLayout_Headings_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать заголовков.
        /// </summary>
        public static string PageLayout_Headings_PrintTooltip {
            get {
                return ResourceManager.GetString("PageLayout_Headings_PrintTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string PageLayout_Headings_View {
            get {
                return ResourceManager.GetString("PageLayout_Headings_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр заголовков.
        /// </summary>
        public static string PageLayout_Headings_ViewTooltip {
            get {
                return ResourceManager.GetString("PageLayout_Headings_ViewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры страницы.
        /// </summary>
        public static string PageLayout_PageSetup {
            get {
                return ResourceManager.GetString("PageLayout_PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область печати.
        /// </summary>
        public static string PageLayout_PrintArea {
            get {
                return ResourceManager.GetString("PageLayout_PrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить область печати.
        /// </summary>
        public static string PageLayout_PrintArea_AddtoPrintArea {
            get {
                return ResourceManager.GetString("PageLayout_PrintArea_AddtoPrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать область печати.
        /// </summary>
        public static string PageLayout_PrintArea_ClearPrintArea {
            get {
                return ResourceManager.GetString("PageLayout_PrintArea_ClearPrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать область печати.
        /// </summary>
        public static string PageLayout_PrintArea_SetPrintArea {
            get {
                return ResourceManager.GetString("PageLayout_PrintArea_SetPrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры листа.
        /// </summary>
        public static string PageLayout_SheetOptions {
            get {
                return ResourceManager.GetString("PageLayout_SheetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета темы.
        /// </summary>
        public static string PageLayout_ThemeColorsTooltip {
            get {
                return ResourceManager.GetString("PageLayout_ThemeColorsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифты темы.
        /// </summary>
        public static string PageLayout_ThemeFontsTooltip {
            get {
                return ResourceManager.GetString("PageLayout_ThemeFontsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темы.
        /// </summary>
        public static string PageLayout_Themes {
            get {
                return ResourceManager.GetString("PageLayout_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вынести вперед.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_BringForward {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вынести на передний план.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_BringToFront {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить содержимое.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_ClearContents {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_ClearContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_Cut {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форматировать ячейки.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_FormatCells {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_FormatCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_HideColumns {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_HideColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_HideRows {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_HideRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гиперссылка.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_Hyperlink {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить ячейки.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_InsertCells {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_InsertCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить колонки.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_InsertColumns {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_InsertColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить строки.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_InsertRows {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_InsertRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_Past {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить ячейки.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_RemoveCells {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_RemoveCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить колонки.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_RemoveColumns {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_RemoveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить гиперссылку.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_RemoveHyperlink {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_RemoveHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить строки.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_RemoveRows {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_RemoveRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вынести назад.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_SendBack {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_SendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вынести на задний план.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_SendBackward {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_UnhideColumns {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_UnhideColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        public static string RadSpreadsheet_ContextMenu_UnhideRows {
            get {
                return ResourceManager.GetString("RadSpreadsheet_ContextMenu_UnhideRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рецензирование.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения.
        /// </summary>
        public static string Review_Changes {
            get {
                return ResourceManager.GetString("Review_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защитить лист.
        /// </summary>
        public static string Review_ProtectSheet {
            get {
                return ResourceManager.GetString("Review_ProtectSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защитить книгу.
        /// </summary>
        public static string Review_ProtectWorkbook {
            get {
                return ResourceManager.GetString("Review_ProtectWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поворот.
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поворот налево.
        /// </summary>
        public static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поворот направо.
        /// </summary>
        public static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрепить области.
        /// </summary>
        public static string View_FreezePanes {
            get {
                return ResourceManager.GetString("View_FreezePanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрепить первый столбец.
        /// </summary>
        public static string View_FreezePanes_FreezeFirstColumn {
            get {
                return ResourceManager.GetString("View_FreezePanes_FreezeFirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрепить верхнюю строку.
        /// </summary>
        public static string View_FreezePanes_FreezeTopRow {
            get {
                return ResourceManager.GetString("View_FreezePanes_FreezeTopRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрепить области.
        /// </summary>
        public static string View_FreezePanes_UnfreezePanes {
            get {
                return ResourceManager.GetString("View_FreezePanes_UnfreezePanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окно.
        /// </summary>
        public static string View_Window {
            get {
                return ResourceManager.GetString("View_Window", resourceCulture);
            }
        }
    }
}
