//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GazRouter.Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelerikResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelerikResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GazRouter.Application.Localization.TelerikResources", typeof(TelerikResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ActivateRow {
            get {
                return ResourceManager.GetString("ActivateRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По алфавиту.
        /// </summary>
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide.
        /// </summary>
        public static string Auto_hide {
            get {
                return ResourceManager.GetString("Auto_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Edit.
        /// </summary>
        public static string BeginEdit {
            get {
                return ResourceManager.GetString("BeginEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string BeginEditAppointment {
            get {
                return ResourceManager.GetString("BeginEditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string BeginInlineEditing {
            get {
                return ResourceManager.GetString("BeginInlineEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Insert.
        /// </summary>
        public static string BeginInsert {
            get {
                return ResourceManager.GetString("BeginInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Cell Edit.
        /// </summary>
        public static string CancelCellEdit {
            get {
                return ResourceManager.GetString("CancelCellEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CancelEditAppointment {
            get {
                return ResourceManager.GetString("CancelEditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Row Edit.
        /// </summary>
        public static string CancelRowEdit {
            get {
                return ResourceManager.GetString("CancelRowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По категориям.
        /// </summary>
        public static string Categorize {
            get {
                return ResourceManager.GetString("Categorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, dd/MM/yy.
        /// </summary>
        public static string ChartAxisLabelDateTimeFormat {
            get {
                return ResourceManager.GetString("ChartAxisLabelDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChartAxisLabelFormat {
            get {
                return ResourceManager.GetString("ChartAxisLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легенда.
        /// </summary>
        public static string ChartChartLegendHeader {
            get {
                return ResourceManager.GetString("ChartChartLegendHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее количество.
        /// </summary>
        public static string ChartChartLegendLinearSeriesFormat {
            get {
                return ResourceManager.GetString("ChartChartLegendLinearSeriesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChartChartTitle {
            get {
                return ResourceManager.GetString("ChartChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChartHorizontalAxisTitle {
            get {
                return ResourceManager.GetString("ChartHorizontalAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemLabel  {0}.
        /// </summary>
        public static string ChartItemLabelFormat {
            get {
                return ResourceManager.GetString("ChartItemLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChartItemToolTipFormat {
            get {
                return ResourceManager.GetString("ChartItemToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Series..
        /// </summary>
        public static string ChartNoDataMessage {
            get {
                return ResourceManager.GetString("ChartNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChartVerticalAxisTitle {
            get {
                return ResourceManager.GetString("ChartVerticalAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string ChartViewNoData {
            get {
                return ResourceManager.GetString("ChartViewNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        public static string ChartViewNoSeries {
            get {
                return ResourceManager.GetString("ChartViewNoSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть.
        /// </summary>
        public static string CollapseHierarchyItem {
            get {
                return ResourceManager.GetString("CollapseHierarchyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string CollectionEditorAdd {
            get {
                return ResourceManager.GetString("CollectionEditorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элементы.
        /// </summary>
        public static string CollectionEditorItems {
            get {
                return ResourceManager.GetString("CollectionEditorItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства.
        /// </summary>
        public static string CollectionEditorProperties {
            get {
                return ResourceManager.GetString("CollectionEditorProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string CollectionEditorRemove {
            get {
                return ResourceManager.GetString("CollectionEditorRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Automatic.
        /// </summary>
        public static string ColorPickerAutomatic {
            get {
                return ResourceManager.GetString("ColorPickerAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row 
        ///@Standard colors.
        /// </summary>
        public static string ColorPickerStandardColors {
            get {
                return ResourceManager.GetString("ColorPickerStandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Theme colors.
        /// </summary>
        public static string ColorPickerThemeColors {
            get {
                return ResourceManager.GetString("ColorPickerThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string ColorSelectorAutomaticColorText {
            get {
                return ResourceManager.GetString("ColorSelectorAutomaticColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета темы.
        /// </summary>
        public static string ColorSelectorMainPaletteHeaderText {
            get {
                return ResourceManager.GetString("ColorSelectorMainPaletteHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недавние цвета.
        /// </summary>
        public static string ColorSelectorRecentColorsHeaderText {
            get {
                return ResourceManager.GetString("ColorSelectorRecentColorsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартные цвета.
        /// </summary>
        public static string ColorSelectorStandardPaletteHeaderText {
            get {
                return ResourceManager.GetString("ColorSelectorStandardPaletteHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CommitCellEdit.
        /// </summary>
        public static string CommitCellEdit {
            get {
                return ResourceManager.GetString("CommitCellEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Commit Edit.
        /// </summary>
        public static string CommitEdit {
            get {
                return ResourceManager.GetString("CommitEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string CommitEditAppointment {
            get {
                return ResourceManager.GetString("CommitEditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateAppointment {
            get {
                return ResourceManager.GetString("CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        public static string DayShort {
            get {
                return ResourceManager.GetString("DayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteAppointment {
            get {
                return ResourceManager.GetString("DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить запись?.
        /// </summary>
        public static string DeleteItemQuestion {
            get {
                return ResourceManager.GetString("DeleteItemQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Dockable.
        /// </summary>
        public static string Dockable {
            get {
                return ResourceManager.GetString("Dockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_AbbreviatedCaseNumber {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_AbbreviatedCaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_AlbumTitle {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_AlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Artist {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Author {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_BookAuthor {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_BookAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_BookTitle {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Broadcaster {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Broadcaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_BroadcastTitle {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_BroadcastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_CaseNumber {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_ChapterNumber {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_ChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_City {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Comments {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_CommentsExampleText {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_CommentsExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Compiler {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Composer {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Conductor {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Conductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_ConferencePublicationName {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_ConferencePublicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Counsel {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Counsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_CountryRegion {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_CountryRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Court {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Day {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_DayAccessed {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_DayAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Department {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Director {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Distributor {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_DOI {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_DOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Edition {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Editor {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_ExampleText {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_ExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Institution {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Interviewee {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Interviewee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Interviewer {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Interviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Inventor {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Inventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Issue {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_JournalName {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_JournalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Medium {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Month {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_MonthAccessed {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_MonthAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_MonthExample {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_MonthExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_NameOfWebsite {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_NameOfWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_NumberOfVolumes {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_NumberOfVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Pages {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_PatentNumber {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_PatentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Performer {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_PeriodicalTitle {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_PeriodicalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_ProducerName {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_ProducerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_ProductionCompany {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_ProductionCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_PublicationTitle {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_PublicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Publisher {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_RecordingNumber {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_RecordingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Report {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_ReportType {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_ShortTitle {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_StandardNumber {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_StandardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_StateProvince {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_StateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Station {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Theater {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Theater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Title {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_TitleExampleText {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_TitleExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Translator {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Type {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_URL {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Version {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Volume {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Writer {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_Year {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_BibliographicProperty_YearAccessed {
            get {
                return ResourceManager.GetString("Documents_BibliographicProperty_YearAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No translated (AG).
        /// </summary>
        public static string Documents_RadRichTextBox_HyperlinkToolTipFormatString {
            get {
                return ResourceManager.GetString("Documents_RadRichTextBox_HyperlinkToolTipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_RadRichTextBox_SectionBreak {
            get {
                return ResourceManager.GetString("Documents_RadRichTextBox_SectionBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_RadRichTextBox_SectionBreak_NextPage {
            get {
                return ResourceManager.GetString("Documents_RadRichTextBox_SectionBreak_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_TableStylesGallery_BuiltInOffice2010TablesHeader {
            get {
                return ResourceManager.GetString("Documents_TableStylesGallery_BuiltInOffice2010TablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_TableStylesGallery_CustomTablesHeader {
            get {
                return ResourceManager.GetString("Documents_TableStylesGallery_CustomTablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_TableStylesGallery_GridTablesHeader {
            get {
                return ResourceManager.GetString("Documents_TableStylesGallery_GridTablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_TableStylesGallery_ListTablesHeader {
            get {
                return ResourceManager.GetString("Documents_TableStylesGallery_ListTablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Documents_TableStylesGallery_PlainTablesHeader {
            get {
                return ResourceManager.GetString("Documents_TableStylesGallery_PlainTablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DrawRelationFrom {
            get {
                return ResourceManager.GetString("DrawRelationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DrawRelationTo {
            get {
                return ResourceManager.GetString("DrawRelationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string EditAppointment {
            get {
                return ResourceManager.GetString("EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditRecurrence {
            get {
                return ResourceManager.GetString("EditRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату.
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите время.
        /// </summary>
        public static string EnterTime {
            get {
                return ResourceManager.GetString("EnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть.
        /// </summary>
        public static string ExpandHierarchyItem {
            get {
                return ResourceManager.GetString("ExpandHierarchyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Extends selection to current unit.
        /// </summary>
        public static string ExtendSelectionToCurrentUnit {
            get {
                return ResourceManager.GetString("ExtendSelectionToCurrentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С учетом регистра.
        /// </summary>
        public static string FilterMatchCase {
            get {
                return ResourceManager.GetString("FilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Floating.
        /// </summary>
        public static string Floating {
            get {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий.
        /// </summary>
        public static string GoToNextAppointment {
            get {
                return ResourceManager.GetString("GoToNextAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий.
        /// </summary>
        public static string GoToPreviousAppointment {
            get {
                return ResourceManager.GetString("GoToPreviousAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите здесь, чтобы добавить новый элемент.
        /// </summary>
        public static string GridViewAlwaysVisibleNewRow {
            get {
                return ResourceManager.GetString("GridViewAlwaysVisibleNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить.
        /// </summary>
        public static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И.
        /// </summary>
        public static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержит.
        /// </summary>
        public static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто.
        /// </summary>
        public static string GridViewFilterDistinctValueNull {
            get {
                return ResourceManager.GetString("GridViewFilterDistinctValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не содержит.
        /// </summary>
        public static string GridViewFilterDoesNotContain {
            get {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заканчивается.
        /// </summary>
        public static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержится в.
        /// </summary>
        public static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Равен.
        /// </summary>
        public static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше чем.
        /// </summary>
        public static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше или равен.
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше чем.
        /// </summary>
        public static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше или равен.
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не содержиться в.
        /// </summary>
        public static string GridViewFilterIsNotContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не равен.
        /// </summary>
        public static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С учетом регистра.
        /// </summary>
        public static string GridViewFilterMatchCase {
            get {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или.
        /// </summary>
        public static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать все.
        /// </summary>
        public static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать строки со значением, что.
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начинается с.
        /// </summary>
        public static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите заголовок столбца сюда, чтобы сгруппировать значения по этому столбцу.
        /// </summary>
        public static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок группы.
        /// </summary>
        public static string GridViewGroupPanelTopText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сгруппировано по:.
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месяц.
        /// </summary>
        public static string MonthShort {
            get {
                return ResourceManager.GetString("MonthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Bottom.
        /// </summary>
        public static string MoveBottom {
            get {
                return ResourceManager.GetString("MoveBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move End.
        /// </summary>
        public static string MoveEnd {
            get {
                return ResourceManager.GetString("MoveEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move First.
        /// </summary>
        public static string MoveFirst {
            get {
                return ResourceManager.GetString("MoveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Home.
        /// </summary>
        public static string MoveHome {
            get {
                return ResourceManager.GetString("MoveHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Last.
        /// </summary>
        public static string MoveLast {
            get {
                return ResourceManager.GetString("MoveLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        public static string MoveLeft {
            get {
                return ResourceManager.GetString("MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Next.
        /// </summary>
        public static string MoveNext {
            get {
                return ResourceManager.GetString("MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move PageDown.
        /// </summary>
        public static string MovePageDown {
            get {
                return ResourceManager.GetString("MovePageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move PageUp.
        /// </summary>
        public static string MovePageUp {
            get {
                return ResourceManager.GetString("MovePageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Previous.
        /// </summary>
        public static string MovePrevious {
            get {
                return ResourceManager.GetString("MovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        public static string MoveRight {
            get {
                return ResourceManager.GetString("MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Top.
        /// </summary>
        public static string MoveTop {
            get {
                return ResourceManager.GetString("MoveTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий.
        /// </summary>
        public static string NextAppointment {
            get {
                return ResourceManager.GetString("NextAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        public static string Pivot_GrandTotal {
            get {
                return ResourceManager.GetString("Pivot_GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение:.
        /// </summary>
        public static string Pivot_Value {
            get {
                return ResourceManager.GetString("Pivot_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий.
        /// </summary>
        public static string PreviousAppointment {
            get {
                return ResourceManager.GetString("PreviousAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартал.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартал.
        /// </summary>
        public static string QuarterShort {
            get {
                return ResourceManager.GetString("QuarterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string RadDataPagerEllipsisString {
            get {
                return ResourceManager.GetString("RadDataPagerEllipsisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string RadDataPagerOf {
            get {
                return ResourceManager.GetString("RadDataPagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница.
        /// </summary>
        public static string RadDataPagerPage {
            get {
                return ResourceManager.GetString("RadDataPagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelationToolTip {
            get {
                return ResourceManager.GetString("RelationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @RemoveItem.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string RibbonBarGalleryButtonMore {
            get {
                return ResourceManager.GetString("RibbonBarGalleryButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Up down button.
        /// </summary>
        public static string RibbonBarGalleryButtonUpDown {
            get {
                return ResourceManager.GetString("RibbonBarGalleryButtonUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Row.
        /// </summary>
        public static string RibbonViewGalleryButtonMore {
            get {
                return ResourceManager.GetString("RibbonViewGalleryButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @More.
        /// </summary>
        public static string RibbonViewGalleryButtonUpDown {
            get {
                return ResourceManager.GetString("RibbonViewGalleryButtonUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Current Item.
        /// </summary>
        public static string SelectCurrentItem {
            get {
                return ResourceManager.GetString("SelectCurrentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the current unit.
        /// </summary>
        public static string SelectCurrentUnit {
            get {
                return ResourceManager.GetString("SelectCurrentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид: День.
        /// </summary>
        public static string SetDayViewMode {
            get {
                return ResourceManager.GetString("SetDayViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид: месяц.
        /// </summary>
        public static string SetMonthViewMode {
            get {
                return ResourceManager.GetString("SetMonthViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид: время.
        /// </summary>
        public static string SetTimelineViewMode {
            get {
                return ResourceManager.GetString("SetTimelineViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SomeDay.
        /// </summary>
        public static string SetToday {
            get {
                return ResourceManager.GetString("SetToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид: Неделя.
        /// </summary>
        public static string SetWeekViewMode {
            get {
                return ResourceManager.GetString("SetWeekViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format string is not in the correct format..
        /// </summary>
        public static string Spreadsheet_ErrorExpressions_FormatStringIncorrectFormat {
            get {
                return ResourceManager.GetString("Spreadsheet_ErrorExpressions_FormatStringIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Spreadsheet_FormatCellsDialog_Number_None {
            get {
                return ResourceManager.GetString("Spreadsheet_FormatCellsDialog_Number_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Spreadsheet_StatusBar_Ready {
            get {
                return ResourceManager.GetString("Spreadsheet_StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОТОВО.
        /// </summary>
        public static string Spreadsheet_StatusBar_ReadyCapital {
            get {
                return ResourceManager.GetString("Spreadsheet_StatusBar_ReadyCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed document.
        /// </summary>
        public static string Tabbed_document {
            get {
                return ResourceManager.GetString("Tabbed_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить до предела.
        /// </summary>
        public static string TileViewItemMaximizeText {
            get {
                return ResourceManager.GetString("TileViewItemMaximizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить.
        /// </summary>
        public static string TileViewItemMinimizeText {
            get {
                return ResourceManager.GetString("TileViewItemMinimizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Линия времени.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop after.
        /// </summary>
        public static string TreeViewDropAfter {
            get {
                return ResourceManager.GetString("TreeViewDropAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop before.
        /// </summary>
        public static string TreeViewDropBefore {
            get {
                return ResourceManager.GetString("TreeViewDropBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop in.
        /// </summary>
        public static string TreeViewDropIn {
            get {
                return ResourceManager.GetString("TreeViewDropIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Drop as root.
        /// </summary>
        public static string TreeViewDropRoot {
            get {
                return ResourceManager.GetString("TreeViewDropRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Select files to upload.
        /// </summary>
        public static string UploadCaptionSelect {
            get {
                return ResourceManager.GetString("UploadCaptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неделя.
        /// </summary>
        public static string WeekShort {
            get {
                return ResourceManager.GetString("WeekShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год.
        /// </summary>
        public static string YearShort {
            get {
                return ResourceManager.GetString("YearShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите время.
        /// </summary>
        public static string Введите_время {
            get {
                return ResourceManager.GetString("Введите время", resourceCulture);
            }
        }
    }
}
