using System.Xml.Serialization;

namespace GazRouter.DataServices.ExchangeServices.AsduDispTask
{
    /// <summary>
    /// Summary description for DispatcherMessage
    /// </summary>
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан программой.
    //     Исполняемая версия:2.0.50727.8009
    //
    //     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
    //     повторной генерации кода.
    // </auto-generated>
    //------------------------------------------------------------------------------



    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DispatcherMessage
    {

        private HeaderSection headerSectionField;

        private DataSection[] dataSectionField;

        private Attachment attachmentField;

        private double versionField;

        public DispatcherMessage()
        {
            this.versionField = 1;
        }

        /// <remarks/>
        public HeaderSection HeaderSection
        {
            get
            {
                return this.headerSectionField;
            }
            set
            {
                this.headerSectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataSection")]
        public DataSection[] DataSection
        {
            get
            {
                return this.dataSectionField;
            }
            set
            {
                this.dataSectionField = value;
            }
        }

        /// <remarks/>
        public Attachment Attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class HeaderSection
    {

        private HeaderSectionIdentifier identifierField;

        private HeaderSectionType typeField;

        private HeaderSectionSender senderField;

        private HeaderSectionReceiver receiverField;

        private HeaderSectionGenerated generatedField;

        private HeaderSectionSend sendField;

        private string subjectField;

        private status statusField;

        private string authorField;

        private string editorField;

        private string commentField;

        private HeaderSectionCarbonCopy carbonCopyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionIdentifier Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionSender Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionReceiver Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionGenerated Generated
        {
            get
            {
                return this.generatedField;
            }
            set
            {
                this.generatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionSend Send
        {
            get
            {
                return this.sendField;
            }
            set
            {
                this.sendField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Editor
        {
            get
            {
                return this.editorField;
            }
            set
            {
                this.editorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionCarbonCopy CarbonCopy
        {
            get
            {
                return this.carbonCopyField;
            }
            set
            {
                this.carbonCopyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionIdentifier
    {

        private string typeField;

        private string valueField;

        public HeaderSectionIdentifier()
        {
            this.typeField = "GlobalID";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionType
    {

        private string idField;

        private dispMsgType valueField;

        public HeaderSectionType()
        {
            this.idField = "DT";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public dispMsgType Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum dispMsgType
    {

        /// <remarks/>
        INSTR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionSender
    {

        private partner idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public partner id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum partner
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("М АСДУ ЕСГ")]
        МАСДУЕСГ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Волгоград")]
        ГПТГВолгоград,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Екатеринбург")]
        ГПТГЕкатеринбург,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Казань")]
        ГПТГКазань,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Краснодар")]
        ГПТГКраснодар,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Махачкала")]
        ГПТГМахачкала,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Москва")]
        ГПТГМосква,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Н.Новгород")]
        ГПТГННовгород,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Самара")]
        ГПТГСамара,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ С.Петербург")]
        ГПТГСПетербург,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Саратов")]
        ГПТГСаратов,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Ставрополь")]
        ГПТГСтаврополь,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Сургут")]
        ГПТГСургут,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Томск")]
        ГПТГТомск,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Уфа")]
        ГПТГУфа,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Ухта")]
        ГПТГУхта,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Чайковский")]
        ГПТГЧайковский,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Югорск")]
        ГПТГЮгорск,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Астрахань")]
        ГПДБАстрахань,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Надым")]
        ГПДБНадым,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Ноябрьск")]
        ГПДБНоябрьск,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Оренбург")]
        ГПДБОренбург,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Уренгой")]
        ГПДБУренгой,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Ямбург")]
        ГПДБЯмбург,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Краснодар")]
        ГПДБКраснодар,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП Переработка")]
        ГППереработка,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ПХГ")]
        ГППХГ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ТГ Беларусь")]
        ГПТГБеларусь,

        /// <remarks/>
        СеверНГ,

        /// <remarks/>
        ЧеченГП,

        /// <remarks/>
        УкрТГ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Сахалин Энерджи")]
        СахалинЭнерджи,

        /// <remarks/>
        Томскнефть,

        /// <remarks/>
        Славнефть,

        /// <remarks/>
        ТомскГП,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП Нефть")]
        ГПНефть,

        /// <remarks/>
        Молдовагаз,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Салым петролеум")]
        Салымпетролеум,

        /// <remarks/>
        ИЦА,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП Межрегионгаз")]
        ГПМежрегионгаз,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП Туркменистан")]
        ГПТуркменистан,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП Казахстан")]
        ГПКазахстан,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Шельф")]
        ГПДБШельф,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП Армения")]
        ГПАрмения,

        /// <remarks/>
        ЯкутГП,

        /// <remarks/>
        НорильскГП,

        /// <remarks/>
        ГрузТГ,

        /// <remarks/>
        УргенчТГ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП ДБ Иркутск")]
        ГПДБИркутск,

        /// <remarks/>
        ЧерноморНГ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ГП Кыргызстан")]
        ГПКыргызстан,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionReceiver
    {

        private partner idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public partner id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionGenerated
    {

        private System.DateTime atField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime at
        {
            get
            {
                return this.atField;
            }
            set
            {
                this.atField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionSend
    {

        private System.DateTime atField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime at
        {
            get
            {
                return this.atField;
            }
            set
            {
                this.atField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum status
    {

        /// <remarks/>
        Consultative,

        /// <remarks/>
        Consultative_Received,

        /// <remarks/>
        Corrected,

        /// <remarks/>
        Agreed,

        /// <remarks/>
        Confirmed,

        /// <remarks/>
        Confirmed_Received,

        /// <remarks/>
        Canceled,

        /// <remarks/>
        Fulfilled,

        /// <remarks/>
        Fulfilled_Recognized,

        /// <remarks/>
        Fulfilled_DO,

        /// <remarks/>
        Fulfilled_Final,

        /// <remarks/>
        Timeout,

        /// <remarks/>
        Expired,

        /// <remarks/>
        Fulfilled_Expired,

        /// <remarks/>
        Fulfilled_DO_Expired,

        /// <remarks/>
        Keep_Violation_Recognized,

        /// <remarks/>
        Keep_Completed,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionCarbonCopy
    {

        private HeaderSectionCarbonCopyReceiver receiverField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HeaderSectionCarbonCopyReceiver Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HeaderSectionCarbonCopyReceiver
    {

        private partner idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public partner id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class DataSection
    {

        private DataSectionIdentifier identifierField;

        private string parameterFullNameField;

        private string valueField;

        private scaleType scaleField;

        private string dimensionField;

        private DataSectionSetpoint setpointField;

        private boolean specialInterestFlagField;

        private bool specialInterestFlagFieldSpecified;

        private boolean holdValueFlagField;

        private bool holdValueFlagFieldSpecified;

        private boolean isFulfilledFlagField;

        private bool isFulfilledFlagFieldSpecified;

        private string commentField;

        private System.DateTime deadlineField;

        private bool deadlineFieldSpecified;

        private string operationStateField;

        private DataSectionHoldRangePlus holdRangePlusField;

        private DataSectionHoldRangeMinus holdRangeMinusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataSectionIdentifier Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParameterFullName
        {
            get
            {
                return this.parameterFullNameField;
            }
            set
            {
                this.parameterFullNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public scaleType Scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dimension
        {
            get
            {
                return this.dimensionField;
            }
            set
            {
                this.dimensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataSectionSetpoint Setpoint
        {
            get
            {
                return this.setpointField;
            }
            set
            {
                this.setpointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public boolean SpecialInterestFlag
        {
            get
            {
                return this.specialInterestFlagField;
            }
            set
            {
                this.specialInterestFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpecialInterestFlagSpecified
        {
            get
            {
                return this.specialInterestFlagFieldSpecified;
            }
            set
            {
                this.specialInterestFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public boolean HoldValueFlag
        {
            get
            {
                return this.holdValueFlagField;
            }
            set
            {
                this.holdValueFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoldValueFlagSpecified
        {
            get
            {
                return this.holdValueFlagFieldSpecified;
            }
            set
            {
                this.holdValueFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public boolean IsFulfilledFlag
        {
            get
            {
                return this.isFulfilledFlagField;
            }
            set
            {
                this.isFulfilledFlagField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsFulfilledFlagSpecified
        {
            get
            {
                return this.isFulfilledFlagFieldSpecified;
            }
            set
            {
                this.isFulfilledFlagFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Deadline
        {
            get
            {
                return this.deadlineField;
            }
            set
            {
                this.deadlineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadlineSpecified
        {
            get
            {
                return this.deadlineFieldSpecified;
            }
            set
            {
                this.deadlineFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OperationState
        {
            get
            {
                return this.operationStateField;
            }
            set
            {
                this.operationStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataSectionHoldRangePlus HoldRangePlus
        {
            get
            {
                return this.holdRangePlusField;
            }
            set
            {
                this.holdRangePlusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataSectionHoldRangeMinus HoldRangeMinus
        {
            get
            {
                return this.holdRangeMinusField;
            }
            set
            {
                this.holdRangeMinusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataSectionIdentifier
    {

        private string typeField;

        private string valueField;

        public DataSectionIdentifier()
        {
            this.typeField = "ASDU_ESG";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum scaleType
    {

        /// <remarks/>
        PACT,

        /// <remarks/>
        PT5M,

        /// <remarks/>
        PT2H,

        /// <remarks/>
        PT24H,

        /// <remarks/>
        P1M,

        /// <remarks/>
        P1Q,

        /// <remarks/>
        P1Y,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataSectionSetpoint
    {

        private setpointType typeField;

        private bool typeFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public setpointType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum setpointType
    {

        /// <remarks/>
        absolute,

        /// <remarks/>
        relative,

        /// <remarks/>
        discrete,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum boolean
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataSectionHoldRangePlus
    {

        private setpointType typeField;

        private bool typeFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public setpointType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class DataSectionHoldRangeMinus
    {

        private setpointType typeField;

        private bool typeFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public setpointType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Attachment
    {

        private string filenameField;

        private object contentField;

        private string commentField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        private string encodingField;

        public Attachment()
        {
            this.encodingField = "base64";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
    }
}