//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GazRouter.Service.Exchange.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GazRouter.Service.Exchange.Lib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos;/&gt;
        ///
        ///  &lt;!-- разделитель строк входного файла--&gt;
        ///  &lt;xsl:param name=&apos;rowDelimiter&apos;&gt;\r?\n&lt;/xsl:param&gt;
        ///
        ///  &lt;!-- преобразуемая информация, во время выполнения подменяется значениями из входных файлов от определенного ДООО  --&gt;
        ///  &lt;!-- ASTRA_IMPORT_CS&lt;ddmmyyyyHHmi&gt;.c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ASTRA_Import_CSHOP {
            get {
                return ResourceManager.GetString("ASTRA_Import_CSHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&apos;2.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&apos;no&apos; indent=&apos;yes&apos; version=&apos;1.0&apos; encoding=&apos;utf-8&apos;/&gt;
        ///
        ///  &lt;!-- разделитель строк входного файла--&gt;
        ///  &lt;xsl:param name=&apos;rowDelimiter&apos;&gt;\r?\n&lt;/xsl:param&gt;
        ///  
        ///  &lt;!-- преобразуемая информация, во время выполнения подменяется значениями из входных файлов от определенного ДООО  --&gt;
        ///
        ///  &lt;xsl:param name=&apos;inputContent&apos; a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ASTRA_Import_PIPE {
            get {
                return ResourceManager.GetString("ASTRA_Import_PIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:tem=&quot;http://tempuri.org/&quot;&gt;
        ///&lt;soap:Header&gt;
        ///&lt;UniqueKey&gt;{template.Id}&lt;/UniqueKey&gt;
        ///&lt;PayloadType&gt;application/psi-go-dpm-14-ims&lt;/PayloadType&gt;
        ///&lt;/soap:Header&gt;
        ///&lt;soap:Body&gt;
        ///&lt;DispatcherMessage version=&quot;1.0&quot;&gt;
        ///&lt;HeaderSection&gt;
        ///&lt;Identifier type=&quot;GlobalID&quot;/&gt;
        ///&lt;Type id=&quot;DT&quot;&gt;EMERG&lt;/Type&gt;
        ///&lt;Sender id=&quot;ГП ТГ Самара&quot; /&gt;
        ///&lt;Receiver id=&quot;{template.EnterpriseAsduId}&quot; /&gt;
        ///&lt;Generated at=&quot;{template.EventDateTime}&quot; /&gt;
        ///&lt;Send at=&quot;{DateTime.Now}&quot; /&gt;
        ///&lt;Subjec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RequestString {
            get {
                return ResourceManager.GetString("RequestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
