//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Xml.Serialization;

namespace GazRouter.DataServices.ExchangeServices {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class XmlMessage {
        
        private XmlMessageDTMessage dTMessageField;
        
        /// <remarks/>
        public XmlMessageDTMessage DTMessage {
            get {
                return this.dTMessageField;
            }
            set {
                this.dTMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlMessageDTMessage {
        
        private XmlMessageDTMessageHeader headerField;
        
        private XmlMessageDTMessageAttribute[] attributesField;
        
        /// <remarks/>
        public XmlMessageDTMessageHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("Attribute", IsNullable=false)]
        public XmlMessageDTMessageAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlMessageDTMessageHeader {
        
        private System.DateTime sendDateField;
        
        private bool sendDateFieldSpecified;
        
        private string receiverField;
        
        private string senderField;
        
        private string globalIdField;
        
        private sbyte senderSeqIdField;
        
        private bool senderSeqIdFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute(DataType="date")]
        public System.DateTime SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool SendDateSpecified {
            get {
                return this.sendDateFieldSpecified;
            }
            set {
                this.sendDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string GlobalId {
            get {
                return this.globalIdField;
            }
            set {
                this.globalIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public sbyte SenderSeqId {
            get {
                return this.senderSeqIdField;
            }
            set {
                this.senderSeqIdField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool SenderSeqIdSpecified {
            get {
                return this.senderSeqIdFieldSpecified;
            }
            set {
                this.senderSeqIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlMessageDTMessageAttribute {
        
        private short keyField;
        
        private sbyte instanceField;
        
        private bool instanceFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public short key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public sbyte instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool instanceSpecified {
            get {
                return this.instanceFieldSpecified;
            }
            set {
                this.instanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
